services:
  db:
    image: mysql:8.0
    container_name: wordpress-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    # Arahkan build ke direktori 'wordpress' tempat Dockerfile dan Composer berada
    build: D:\wordpress-magang\furniture hanvital
    container_name: wordpress-app
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # Peta volume 'wp-content' untuk menyinkronkan plugin, tema, dan unggahan
      - ./wordpress/wp-content:/var/www/html/wp-content
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db_data: {}